theme: jekyll-theme-architect
baseurl: "/my_story"
url: "https://ptenteromano.github.io/"
future: true
timezone: America/New_York
title: my_story
description: From Soldier to Software
github:
  repository_url: https://github.com/ptenteromano
