theme: jekyll-theme-modernist
baseurl: "/my_story"
url: "https://ptenteromano.github.io/"
future: true
timezone: America/New_York
title: my_story
description: From Soldier to Software
github:
  is_project_page: false
